### ISSUE TITLE
Input with brackets causes audio conversion to fail

### ISSUE THREAD

**Issue by spitemim** [calzoneman/aeiou#11]
Any text containing `[` or `]` is rejected by the /tts endpoint. This started within the past hour or two, and although I'm pretty sure it's not an issue on my end, I don't have another device to test this theory.

Making a GET request to /tts with the text parameter set to either `[` or `%5B` (URL encoded left bracket), yields the following result:

```
Unable to process input "["
```

Obviously a single `[` is not a syntactically valid DecTalk instruction, but the same error occurs with a syntactically valid program like the following:

```
[:phoneme on]
aeiou
```

Which yields this result:

```
Unable to process input "[:phoneme on] aeiou"
```

Since this problem seemed to start well after the most recent commit, I assume you're either doing some tinkering on the production instance, or something has gone horribly wrong with some software on your server. I was making a lot of download requests earlier while making a song. Could that be it?

---

On a related note, I think a possibility to make debugging easier would be to include more relevant information about processing errors on the error page. For example, some estimate of where along the pipeline the error occured would be nice. Did the webserver crash handling the request, or did DecTalk return an error code?

**Comment by calzoneman** [comment]
I don't think that the bracket is related.  It seems like the DECTalk shared memory license counter got stuck, which is a known issue that I haven't fixed yet, but I guess I will have to do that now.  I restarted it, so it should be working now.

As an aside, the implementation turns phonemes on automatically, so you don't need to begin your messages with `[:phoneme on]`.
