### ISSUE TITLE
Can you change it to google tts?

### ISSUE THREAD

**Issue by mebl1ss** [calzoneman/aeiou#15]
Can you change it to google tts?

**Comment by calzoneman** [comment]
The point of this software is to expose an API for DECtalk specifically.  If you wish to make use of more modern TTS engines, there are probably already more convenient ways for you to do so.  To use your example specifically, Google provides [documentation](https://cloud.google.com/text-to-speech/docs/basics) on how to integrate directly with their text to speech API, you don't need an additional wrapper like in this repository.
