### ISSUE TITLE
What version/voice settings does your version of DECtalk use?

### ISSUE THREAD

**Issue by spitemim** [calzoneman/aeiou#16]
https://github.com/dectalk/dectalk compiles on Linux now, but all the default voices sound very different to the ones on tts.cyzon.us. What version of DECtalk is running on tts.cyzon.us, and are you using extra modifiers to change things like the default pitch, voice speed, etc?

**Comment by calzoneman** [comment]
Hi,

I'm using the DECtalk 4.61 Windows release from here: http://theflameofhope.co/dectalkreader1/.

[The TTS handle is reinitialized between requests](https://github.com/calzoneman/aeiou/blob/master/decwav/decwav/decwav.cpp#L14-L59); the only non-default setting is to enable phonemes by default, which doesn't affect the sound of the voice, just whether phoneme commands are parsed.
