### ISSUE TITLE
May we have .WAV export?

### ISSUE THREAD

**Issue by NeuroNoNeuro** [calzoneman/aeiou#7]
Found this site here, and I really enjoy the DECTalk 'sound'.  May we have the option to export the spoken phrases to .WAV?

Found your GitHub from this site here:  http://tts.cyzon.us/

**Comment by calzoneman** [comment]
The wav audio is provided by calling /tts, e.g. `http://tts.cyzon.us/tts?text=sample%20text`.  This is what that little demonstration on the main page is doing behind the scenes.

A successful `GET` to `/tts` with URL-encoded text in the `text` parameter will return a 302 redirect to a (temporary) wav file holding the output of speaking the text.  There is a limit of 1024 characters per message.

**Comment by NeuroNoNeuro** [comment]
Neat-o!  Thank you for the help.

**Comment by calzoneman** [comment]
Closing in favor of #8.
